version: "3.8"
services:
  sqldashdb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: stiv
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdash
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
